//! Word universe (W) — 34,487 English words with 8-bit structural signature.
//!
//! Sources:
//!   - CMU Pronouncing Dictionary (phonological bits 0,1,2,5,7)
//!   - WordNet (morphological/semantic bits 3,4,6)
//!
//! Signature bits:
//!   bit0  polysyllabic      syllable_count >= 2          (CMU)
//!   bit1  non_init_stress   primary stress not on syl 1  (CMU)
//!   bit2  vowel_initial     first phoneme is vowel        (CMU)
//!   bit3  inflected         surface form != any lemma     (WordNet)
//!   bit4  has_derivational  has derivationally related    (WordNet)
//!   bit5  phono_dense       consonant clusters > 2        (CMU)
//!   bit6  lemma_is_noun     primary synset is noun        (WordNet)
//!   bit7  three_plus_syls   syllable_count >= 3           (CMU)

use std::cmp::Ordering;

/// A word element in the W universe.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Word {
    /// The word string (lowercase, ASC7-normalized)
    pub text: String,
    /// 8-bit structural signature
    pub sig: u8,
}

impl Word {
    /// Canonical byte representation for digest/Merkle use.
    /// Format: sig byte followed by UTF-8 text bytes.
    pub fn canonical_bytes(&self) -> Vec<u8> {
        let mut b = Vec::with_capacity(1 + self.text.len());
        b.push(self.sig);
        b.extend_from_slice(self.text.as_bytes());
        b
    }

    /// Parse signature bits from precomputed fields.
    pub fn sig8(
        syllables: usize,
        stress_initial: bool,
        vowel_initial: bool,
        inflected: bool,
        has_derivational: bool,
        phono_dense: bool,
        lemma_is_noun: bool,
    ) -> u8 {
        let b0 = if syllables >= 2 { 1u8 } else { 0 };
        let b1 = if !stress_initial { 1 } else { 0 };
        let b2 = if vowel_initial { 1 } else { 0 };
        let b3 = if inflected { 1 } else { 0 };
        let b4 = if has_derivational { 1 } else { 0 };
        let b5 = if phono_dense { 1 } else { 0 };
        let b6 = if lemma_is_noun { 1 } else { 0 };
        let b7 = if syllables >= 3 { 1u8 } else { 0 };
        b0 | (b1 << 1) | (b2 << 2) | (b3 << 3) | (b4 << 4) | (b5 << 5) | (b6 << 6) | (b7 << 7)
    }

    /// Bit legend for the 8-bit signature.
    pub fn bit_legend() -> [&'static str; 8] {
        [
            "polysyllabic",
            "non_init_stress",
            "vowel_initial",
            "inflected",
            "has_derivational",
            "phono_dense",
            "lemma_is_noun",
            "three_plus_syls",
        ]
    }
}

/// Canonical total order: sig ascending, then text lexicographic.
pub fn canonical_cmp(a: &Word, b: &Word) -> Ordering {
    a.sig.cmp(&b.sig).then_with(|| a.text.cmp(&b.text))
}

/// Absolute "distance" between two words: Hamming distance on sig bits.
/// Used by WITNESS_NEAREST with metric=HAMMING_SIG.
pub fn sig_distance(a: &Word, b: &Word) -> u32 {
    (a.sig ^ b.sig).count_ones()
}

/// Parse a word element from a string token.
/// Accepts bare lowercase words: "hello", "run", etc.
/// Returns None if the string is empty or contains non-ASCII.
pub fn parse_elem(s: &str) -> Option<Word> {
    let t = s.trim().to_ascii_lowercase();
    if t.is_empty() || !t.is_ascii() {
        return None;
    }
    // Sig is unknown at parse time without CMU/WN data.
    // Returns a Word with sig=0 as a lookup key; the caller
    // must resolve the full sig via build_word() or a lookup table.
    Some(Word { text: t, sig: 0 })
}

/// Build the word universe from an embedded TSV data file.
///
/// The TSV is generated by scripts/build_word_universe.py and
/// embedded at compile time via include_str!.
/// Format per line: word<TAB>sig (decimal 0-255)
///
/// Returns words sorted by canonical_cmp.
pub fn build_word_universe() -> Vec<Word> {
    let data = include_str!("../data/word_universe.tsv");
    let mut words: Vec<Word> = data
        .lines()
        .filter(|l| !l.is_empty() && !l.starts_with('#'))
        .filter_map(|line| {
            let mut parts = line.splitn(2, '\t');
            let text = parts.next()?.trim().to_string();
            let sig: u8 = parts.next()?.trim().parse().ok()?;
            Some(Word { text, sig })
        })
        .collect();
    words.sort_by(canonical_cmp);
    words.dedup_by(|a, b| a.text == b.text && { true });
    words
}

/// Check if a universe name refers to the word universe.
pub fn is_word_universe(u: &str) -> bool {
    matches!(u.to_ascii_uppercase().as_str(), "WORD" | "W" | "WORDNET")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sig8_monosyllabic_noun() {
        // "dog": 1 syllable, initial stress, consonant-initial,
        // not inflected, no derivational, low phono density, noun, <3 syls
        let s = Word::sig8(1, true, false, false, false, false, true);
        assert_eq!(s & 1, 0, "bit0: monosyllabic");
        assert_eq!((s >> 1) & 1, 0, "bit1: initial stress");
        assert_eq!((s >> 2) & 1, 0, "bit2: consonant-initial");
        assert_eq!((s >> 6) & 1, 1, "bit6: lemma is noun");
        assert_eq!((s >> 7) & 1, 0, "bit7: < 3 syllables");
    }

    #[test]
    fn sig8_polysyllabic_verb() {
        // "abandon": 3 syllables, non-initial stress, vowel-initial,
        // not inflected, has derivational, phono dense, not noun, 3+ syls
        let s = Word::sig8(3, false, true, false, true, true, false);
        assert_eq!(s & 1, 1,       "bit0: polysyllabic");
        assert_eq!((s >> 1) & 1, 1, "bit1: non-initial stress");
        assert_eq!((s >> 2) & 1, 1, "bit2: vowel-initial");
        assert_eq!((s >> 6) & 1, 0, "bit6: not noun");
        assert_eq!((s >> 7) & 1, 1, "bit7: 3+ syllables");
    }

    #[test]
    fn canonical_cmp_orders_by_sig_then_text() {
        let a = Word { text: "zoo".to_string(), sig: 0 };
        let b = Word { text: "ant".to_string(), sig: 1 };
        let c = Word { text: "ape".to_string(), sig: 1 };
        assert!(canonical_cmp(&a, &b).is_lt(), "lower sig first");
        assert!(canonical_cmp(&b, &c).is_lt(), "same sig: alpha order");
    }

    #[test]
    fn sig_distance_identical() {
        let a = Word { text: "run".to_string(), sig: 0b10110101 };
        let b = Word { text: "ran".to_string(), sig: 0b10110101 };
        assert_eq!(sig_distance(&a, &b), 0);
    }

    #[test]
    fn sig_distance_one_bit() {
        let a = Word { text: "run".to_string(), sig: 0b00000001 };
        let b = Word { text: "ran".to_string(), sig: 0b00000000 };
        assert_eq!(sig_distance(&a, &b), 1);
    }
    #[test]
    fn word_universe_size_matches_certified() {
        let w = build_word_universe();
        assert_eq!(w.len(), 34_487,
            "word universe size changed — regenerate data/word_universe.tsv");
    }

    #[test]
    fn word_universe_sorted_and_unique() {
        let w = build_word_universe();
        for i in 1..w.len() {
            assert!(canonical_cmp(&w[i-1], &w[i]).is_lt(),
                "universe not strictly sorted at index {}: {:?} >= {:?}",
                i, w[i-1].text, w[i].text);
        }
    }

}
